<?php

/* Set internal character encoding to UTF-8 */
mb_internal_encoding("UTF-8");

// Per default, define there is no copy to send
$is_receipt_asked = false;

// Timezone to use
$timezone = "Europe/Paris";

// Define the range of each field between a *_min & *_max key's value
$field_len_list = array(
    'firstname_min' => 2, 'firstname_max' => 32,
    'secondname_min' => 2, 'secondname_max' => 32,
    'email_min' => 8, 'email_max' => 32,
    'subject_min' => 8, 'subject_max' => 48,
    'body_min' => 64, 'body_max' => 2048
);

// Define the range for adding a prefix for subject & body field once the mail is sended
$prefix_len = array(
    'prefix_subject_min' => 1, 'prefix_subject_max' => 16,
    'prefix_body_min' => 1, 'prefix_body_max' => 512,
);

$mail_form = array(
    0 => array(
        'id' => 'firstname', 
        'name' => 'firstname',
        'readable' => 'First name', 
        'type' => 'text', 
        'htmltag' => 'input', 
        'placeholder' => 'Jean',
    ),

    1 => array(
        'id' => 'secondname',
        'name' => 'secondname',
        'readable' => 'Second name',
        'type' => 'text',
        'htmltag' => 'input',
        'placeholder' => 'Dupont',
    ),

    2 => array(
        'id' => 'email',
        'name' => 'email',
        'readable' => 'Your e-mail address',
        'type' => 'text',
        'htmltag' => 'email',
        'placeholder' => 'foo@bar.org',
    ),

    3 => array(
        'id' => 'subject',
        'name' => 'subject',
        'readable' => 'Subject of your message',
        'type' => 'text',
        'htmltag' => 'input',
        'placeholder' => 'Subject of your message',
    ),

    4 => array(
        'id' => 'body',
        'name' => 'body',
        'readable' => 'Type your message here',
        'type' => 'text',
        'htmltag' => 'textarea',
        'placeholder' => 'Type your message here',
    )

);

// Filters for pattern matching, no need for e-mail because 'FILTER_VALIDATE_EMAIL' is already nicely doing it
$filter_names = "/^\p{Latin}+((?:-|\h)\p{Latin}+)*$/";
$filter_prefix = "/[\p{nD}\p{Latin}\p{P}\p{S}\h]/g";

// This variable is ugly, and you know it. Fix it !
$document_root = "/var/www/localhost/htdocs/checking_form/"; // This path has to be ended with a slash ('/')
$locations = array(
    "pending_mails"         => $document_root . "temp_mail_directory/",
    "logs_mail"             => $document_root . "mail_dir/",
    "logs_mail_accepted"    => $document_root . "mail_dir/ACCEPTED/",
    "logs_mail_rejected"    => $document_root . "mail_dir/REJECTED/"
);

/*$non_trusty_esp_domain = array(
    "yopmail"       =>  array(
        "1xp.fr",
        "cpc.cx",
        "1xp.fr",
        "cpc.cx",
        "0cd.cn",
        "prc.cx",
        "b7s.ru",
        "ab34.fr",
        "ves.ink",
        "q0.us.to",
        "zx81.ovh",
        "wishy.fr",
        "bmn.ch.ma",
        "iya.fr.nf",
        "sdj.fr.nf",
        "afw.fr.nf",
        "mail34.fr",
        "mynes.com",
        "dao.pp.ua",
        "nori24.tv",
        "lerch.ovh",
        "six25.biz",
        "ywzmb.top",
        "isep.fr.nf",
        "noreply.fr",
        "pliz.fr.nf",
        "noyp.fr.nf",
        "zouz.fr.nf",
        "hunnur.com",
        "wxcv.fr.nf",
        "zorg.fr.nf",
        "imap.fr.nf",
        "redi.fr.nf",
        "dlvr.us.to",
        "y.iotf.net",
        "zinc.fr.nf",
        "ym.cypi.fr",
        "yop.too.li",
        "dmts.fr.nf",
        "binich.com",
        "wzofit.com",
        "enpa.rf.gd",
        "jmail.fr.nf",
        "zimel.fr.cr",
        "yaloo.fr.nf",
        "jinva.fr.nf",
        "ag.prout.be",
        "ba.prout.be",
        "es.prout.be",
        "us.prout.be",
        "ealea.fr.nf",
        "nomes.fr.nf",
        "yop.kd2.org",
        "alves.fr.nf",
        "bibi.biz.st",
        "ymail.rr.nu",
        "bboys.fr.nf",
        "ma.ezua.com",
        "ma.zyns.com",
        "mai.25u.com",
        "nomes.fr.cr",
        "autre.fr.nf",
        "lsyx0.rr.nu",
        "tweet.fr.nf",
        "pamil.1s.fr",
        "pamil.fr.nf",
        "ymail.1s.fr",
        "15963.fr.nf",
        "popol.fr.nf",
        "pmail.1s.fr",
        "flobo.fr.nf",
        "toolbox.ovh",
        "bin-ich.com",
        "sindwir.com",
        "mabal.fr.nf",
        "degap.fr.nf",
        "yop.uuii.in",
        "jetable.org",
        "a.kwtest.io",
        "pasdus.fr.cr",
        "gland.xxl.st",
        "nospam.fr.nf",
        "azeqsd.fr.nf",
        "le.monchu.fr",
        "nikora.fr.nf",
        "sendos.fr.nf",
        "cubox.biz.st",
        "fhpfhp.fr.nf",
        "c-eric.fr.nf",
        "c-eric.fr.cr",
        "bahoo.biz.st",
        "upc.infos.st",
        "gggggg.fr.cr",
        "spam.aleh.de",
        "alphax.fr.nf",
        "habenwir.com",
        "ist-hier.com",
        "sind-wir.com",
        "sindhier.com",
        "wir-sind.com",
        "myself.fr.nf",
        "yop.mabox.eu",
        "vip.ep77.com",
        "email.jjj.ee",
        "druzik.pp.ua",
        "flaimenet.ir",
        "yahooz.xxl.st",
        "tiscali.fr.cr",
        "altrans.fr.nf",
        "yoptruc.fr.nf",
        "kyuusei.fr.nf",
        "ac-cool.c4.fr",
        "certexx.fr.nf",
        "dede.infos.st",
        "sake.prout.be",
        "eureka.0rg.fr",
        "yotmail.fr.nf",
        "miloras.fr.nf",
        "nikora.biz.st",
        "cabiste.fr.nf",
        "galaxim.fr.nf",
        "fuppurge.info",
        "doviaso.fr.cr",
        "pitiful.pp.ua",
        "ggmail.biz.st",
        "dis.hopto.org",
        "yop.kyriog.fr",
        "icidroit.info",
        "yop.mc-fly.be",
        "spam.9001.ovh",
        "tmp.x-lab.net",
        "mail.hsmw.net",
        "y.dldweb.info",
        "haben-wir.com",
        "sind-hier.com",
        "adresse.fr.cr",
        "temp.ig96.net",
        "assurmail.net",
        "yop.smeux.com",
        "alyxgod.rf.gd",
        "mailadresi.tk",
        "aze.kwtest.io",
        "mail.3a88.dev",
        "mailbox.biz.st",
        "elmail.4pu.com",
        "carioca.biz.st",
        "mickaben.fr.nf",
        "mickaben.fr.cr",
        "ac-malin.fr.nf",
        "gimuemoa.fr.nf",
        "woofidog.fr.nf",
        "rygel.infos.st",
        "cheznico.fr.cr",
        "contact.biz.st",
        "rapidefr.fr.nf",
        "calendro.fr.nf",
        "calima.asso.st",
        "cobal.infos.st",
        "terre.infos.st",
        "imails.asso.st",
        "warlus.asso.st",
        "carnesa.biz.st",
        "jackymel.xl.cx",
        "mail.tbr.fr.nf",
        "webstore.fr.nf",
        "freemail.fr.cr",
        "mr-email.fr.nf",
        "abo-free.fr.nf",
        "courrier.fr.cr",
        "ymail.ploki.fr",
        "mailsafe.fr.nf",
        "mail.jab.fr.cr",
        "testkkk.zik.dj",
        "sirttest.us.to",
        "yop.moolee.net",
        "antispam.fr.nf",
        "machen-wir.com",
        "adresse.biz.st",
        "poubelle.fr.nf",
        "lacraffe.fr.nf",
        "gladogmi.fr.nf",
        "yopmail.ozm.fr",
        "mail.yabes.ovh",
        "totococo.fr.nf",
        "miistermail.fr",
        "yopmail.kro.kr",
        "freemail.biz.st",
        "skynet.infos.st",
        "readmail.biz.st",
        "frostmail.fr.nf",
        "frostmail.fr.cr",
        "pitimail.xxl.st",
        "mickaben.biz.st",
        "mickaben.xxl.st",
        "internaut.us.to",
        "askold.prout.be",
        "poubelle-du.net",
        "mondial.asso.st",
        "randol.infos.st",
        "himail.infos.st",
        "sendos.infos.st",
        "nidokela.biz.st",
        "likeageek.fr.nf",
        "mcdomaine.fr.nf",
        "emaildark.fr.nf",
        "mymail.ns01.biz",
        "cookie007.fr.nf",
        "tagara.infos.st",
        "pokemons1.fr.nf",
        "spam.quillet.eu",
        "desfrenes.fr.nf",
        "mymail.infos.st",
        "mail.i-dork.com",
        "mail.berwie.com",
        "mesemails.fr.nf",
        "dripzgaming.com",
        "mymaildo.kro.kr",
        "dann.mywire.org",
        "mymailbox.xxl.st",
        "mail.xstyled.net",
        "dreamgreen.fr.nf",
        "contact.infos.st",
        "mess-mails.fr.nf",
        "omicron.token.ro",
        "torrent411.fr.nf",
        "test.inclick.net",
        "ssi-bsn.infos.st",
        "webclub.infos.st",
        "addedbyjc.0rg.fr",
        "vigilantkeep.net",
        "actarus.infos.st",
        "whatagarbage.com",
        "yopmail.ploki.fr",
        "test-infos.fr.nf",
        "mail-mario.fr.nf",
        "dispo.sebbcn.net",
        "ym.digi-value.fr",
        "adresse.infos.st",
        "ypmail.sehier.fr",
        "pixelgagnant.net",
        "m.tartinemoi.com",
        "suck.my-vigor.de",
        "ggamess.42web.io",
        "mail.nuox.eu.org",
        "cool.fr.nf",
        "courriel.fr.nf",
        "jetable.fr.nf",
        "mega.zik.dj",
        "moncourrier.fr.nf",
        "monemail.fr.nf",
        "monmail.fr.nf",
        "nomail.xl.cx",
        "nospam.ze.tc",
        "speed.1s.fr",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net0cd.cn",
        "prc.cx",
        "b7s.ru",
        "ab34.fr",
        "ves.ink",
        "q0.us.to",
        "zx81.ovh",
        "wishy.fr",
        "bmn.ch.ma",
        "iya.fr.nf",
        "sdj.fr.nf",
        "afw.fr.nf",
        "mail34.fr",
        "mynes.com",
        "dao.pp.ua",
        "nori24.tv",
        "lerch.ovh",
        "six25.biz",
        "ywzmb.top",
        "isep.fr.nf",
        "noreply.fr",
        "pliz.fr.nf",
        "noyp.fr.nf",
        "zouz.fr.nf",
        "hunnur.com",
        "wxcv.fr.nf",
        "zorg.fr.nf",
        "imap.fr.nf",
        "redi.fr.nf",
        "dlvr.us.to",
        "y.iotf.net",
        "zinc.fr.nf",
        "ym.cypi.fr",
        "yop.too.li",
        "dmts.fr.nf",
        "binich.com",
        "wzofit.com",
        "enpa.rf.gd",
        "jmail.fr.nf",
        "zimel.fr.cr",
        "yaloo.fr.nf",
        "jinva.fr.nf",
        "ag.prout.be",
        "ba.prout.be",
        "es.prout.be",
        "us.prout.be",
        "ealea.fr.nf",
        "nomes.fr.nf",
        "yop.kd2.org",
        "alves.fr.nf",
        "bibi.biz.st",
        "ymail.rr.nu",
        "bboys.fr.nf",
        "ma.ezua.com",
        "ma.zyns.com",
        "mai.25u.com",
        "nomes.fr.cr",
        "autre.fr.nf",
        "lsyx0.rr.nu",
        "tweet.fr.nf",
        "pamil.1s.fr",
        "pamil.fr.nf",
        "ymail.1s.fr",
        "15963.fr.nf",
        "popol.fr.nf",
        "pmail.1s.fr",
        "flobo.fr.nf",
        "toolbox.ovh",
        "bin-ich.com",
        "sindwir.com",
        "mabal.fr.nf",
        "degap.fr.nf",
        "yop.uuii.in",
        "jetable.org",
        "a.kwtest.io",
        "pasdus.fr.cr",
        "gland.xxl.st",
        "nospam.fr.nf",
        "azeqsd.fr.nf",
        "le.monchu.fr",
        "nikora.fr.nf",
        "sendos.fr.nf",
        "cubox.biz.st",
        "fhpfhp.fr.nf",
        "c-eric.fr.nf",
        "c-eric.fr.cr",
        "bahoo.biz.st",
        "upc.infos.st",
        "gggggg.fr.cr",
        "spam.aleh.de",
        "alphax.fr.nf",
        "habenwir.com",
        "ist-hier.com",
        "sind-wir.com",
        "sindhier.com",
        "wir-sind.com",
        "myself.fr.nf",
        "yop.mabox.eu",
        "vip.ep77.com",
        "email.jjj.ee",
        "druzik.pp.ua",
        "flaimenet.ir",
        "yahooz.xxl.st",
        "tiscali.fr.cr",
        "altrans.fr.nf",
        "yoptruc.fr.nf",
        "kyuusei.fr.nf",
        "ac-cool.c4.fr",
        "certexx.fr.nf",
        "dede.infos.st",
        "sake.prout.be",
        "eureka.0rg.fr",
        "yotmail.fr.nf",
        "miloras.fr.nf",
        "nikora.biz.st",
        "cabiste.fr.nf",
        "galaxim.fr.nf",
        "fuppurge.info",
        "doviaso.fr.cr",
        "pitiful.pp.ua",
        "ggmail.biz.st",
        "dis.hopto.org",
        "yop.kyriog.fr",
        "icidroit.info",
        "yop.mc-fly.be",
        "spam.9001.ovh",
        "tmp.x-lab.net",
        "mail.hsmw.net",
        "y.dldweb.info",
        "haben-wir.com",
        "sind-hier.com",
        "adresse.fr.cr",
        "temp.ig96.net",
        "assurmail.net",
        "yop.smeux.com",
        "alyxgod.rf.gd",
        "mailadresi.tk",
        "aze.kwtest.io",
        "mail.3a88.dev",
        "mailbox.biz.st",
        "elmail.4pu.com",
        "carioca.biz.st",
        "mickaben.fr.nf",
        "mickaben.fr.cr",
        "ac-malin.fr.nf",
        "gimuemoa.fr.nf",
        "woofidog.fr.nf",
        "rygel.infos.st",
        "cheznico.fr.cr",
        "contact.biz.st",
        "rapidefr.fr.nf",
        "calendro.fr.nf",
        "calima.asso.st",
        "cobal.infos.st",
        "terre.infos.st",
        "imails.asso.st",
        "warlus.asso.st",
        "carnesa.biz.st",
        "jackymel.xl.cx",
        "mail.tbr.fr.nf",
        "webstore.fr.nf",
        "freemail.fr.cr",
        "mr-email.fr.nf",
        "abo-free.fr.nf",
        "courrier.fr.cr",
        "ymail.ploki.fr",
        "mailsafe.fr.nf",
        "mail.jab.fr.cr",
        "testkkk.zik.dj",
        "sirttest.us.to",
        "yop.moolee.net",
        "antispam.fr.nf",
        "machen-wir.com",
        "adresse.biz.st",
        "poubelle.fr.nf",
        "lacraffe.fr.nf",
        "gladogmi.fr.nf",
        "yopmail.ozm.fr",
        "mail.yabes.ovh",
        "totococo.fr.nf",
        "miistermail.fr",
        "yopmail.kro.kr",
        "freemail.biz.st",
        "skynet.infos.st",
        "readmail.biz.st",
        "frostmail.fr.nf",
        "frostmail.fr.cr",
        "pitimail.xxl.st",
        "mickaben.biz.st",
        "mickaben.xxl.st",
        "internaut.us.to",
        "askold.prout.be",
        "poubelle-du.net",
        "mondial.asso.st",
        "randol.infos.st",
        "himail.infos.st",
        "sendos.infos.st",
        "nidokela.biz.st",
        "likeageek.fr.nf",
        "mcdomaine.fr.nf",
        "emaildark.fr.nf",
        "mymail.ns01.biz",
        "cookie007.fr.nf",
        "tagara.infos.st",
        "pokemons1.fr.nf",
        "spam.quillet.eu",
        "desfrenes.fr.nf",
        "mymail.infos.st",
        "mail.i-dork.com",
        "mail.berwie.com",
        "mesemails.fr.nf",
        "dripzgaming.com",
        "mymaildo.kro.kr",
        "dann.mywire.org",
        "mymailbox.xxl.st",
        "mail.xstyled.net",
        "dreamgreen.fr.nf",
        "contact.infos.st",
        "mess-mails.fr.nf",
        "omicron.token.ro",
        "torrent411.fr.nf",
        "test.inclick.net",
        "ssi-bsn.infos.st",
        "webclub.infos.st",
        "addedbyjc.0rg.fr",
        "vigilantkeep.net",
        "actarus.infos.st",
        "whatagarbage.com",
        "yopmail.ploki.fr",
        "test-infos.fr.nf",
        "mail-mario.fr.nf",
        "dispo.sebbcn.net",
        "ym.digi-value.fr",
        "adresse.infos.st",
        "ypmail.sehier.fr",
        "pixelgagnant.net",
        "m.tartinemoi.com",
        "suck.my-vigor.de",
        "ggamess.42web.io",
        "mail.nuox.eu.org",
        "cool.fr.nf",
        "courriel.fr.nf",
        "jetable.fr.nf",
        "mega.zik.dj",
        "moncourrier.fr.nf",
        "monemail.fr.nf",
        "monmail.fr.nf",
        "nomail.xl.cx",
        "nospam.ze.tc",
        "speed.1s.fr",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net"
    ),

    "guerillamail"  =>  array(
        "sharklasers.com",
        "guerrillamail.info",
        "grr.la",
        "guerrillamail.biz",
        "guerrillamail.com",
        "guerrillamail.de",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "pokemail.net",
        "spam4.me"
    ),

    "10minutemail"  =>  array(
        "dcobe.com"
    ),

    "tempmail"      =>  array(
        "aleitar.com"
    ),

    "emailondeck"   =>  array(
        "instrete.com"
    )
);*/
